set(MOBILE_DEVICE ON)

set(ARCH_FLAGS "-g -march=armv8-a+crc -mtune=cortex-a75 -funsafe-math-optimizations")

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${ARCH_FLAGS}"  CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${ARCH_FLAGS}" CACHE STRING "" FORCE)
set(CMAKE_ASM_FLAGS "${CMAKE_ASM_FLAGS} ${ARCH_FLAGS}" CACHE STRING "" FORCE)

set(USING_GLES2 ON)
set(USING_EGL ON)
set(USING_FBDEV ON)
set(USE_WAYLAND_WSI ON)
set(USING_X11_VULKAN OFF CACHE BOOL "" FORCE)
